apiVersion: v1
kind: Service
metadata:
   name: mongo
   labels:
     run: mongo
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32001
    protocol: TCP
  selector:
    run: mongo
    
